name: Vulcan Demo

on:
  push
  # workflow_dispatch:

jobs:
  vulcan:
    runs-on: self-hosted

    steps:
      - name: Test vulcan action
        uses: HansolChoe/vulcan-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}\
          path: vulcan_target